db:
  url: "jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
  driverClassName: "org.postgresql.Driver"
  user: "![YNPerQB1HxJ8SxfbAjl+aPOroKQ5C0UKaY54z516Wbg=]"
  password: "![ciDRXRjYv3K6CM26ihTJynCtn+Y5q53KIRM4CZplsck=]"
  
http:
  host: "0.0.0.0"
  port: "8081"
  

  